version: "3"

networks:
  dirtybitsnetwork:
    name: dirtybitsnetwork
    driver: bridge

services:
  auth_web:
    build: .
    container_name: auth_web
    command: >
      sh -c "python3 manage.py wait_for_db &&
             gunicorn auth.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=auth_db
      - DB_NAME=auth
      - DB_USER=server
      - DB_PASSWORD=server
    networks:
      - dirtybitsnetwork
    depends_on:
      - auth_db
  auth_db:
    image: postgres
    container_name: auth_db
    environment:
      - POSTGRES_DB=auth
      - POSTGRES_USER=server
      - POSTGRES_PASSWORD=server
    ports:
      - "5432:5432"
    networks:
      - dirtybitsnetwork
