# Generated by Django 3.2.6 on 2021-09-19 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="passwordchange",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
