# Generated by Django 3.2.6 on 2021-10-23 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_passwordchange_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="profile_pic",
            field=models.TextField(
                default="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSEQKASvktw8z6UeZ_lqqo01vP22M7Zca9EIw&usqp=CAU"
            ),
        ),
    ]
