# Generated by Django 3.2.6 on 2022-01-08 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20220108_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('easy', models.IntegerField(blank=True, default=0, null=True)),
                ('medium', models.IntegerField(blank=True, default=0, null=True)),
                ('hard', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
