# Generated by Django 3.2.6 on 2022-01-15 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_staticdata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="profile_pic",
            field=models.TextField(
                default="https://res.cloudinary.com/hhikcz56h/image/upload/v1641823025/Public/avatar1_wx1j8u.png"
            ),
        ),
    ]
