# Generated by Django 3.2.6 on 2022-01-29 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticdata',
            name='avatar_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
