# Generated by Django 3.2.6 on 2022-01-29 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_staticdata_avatar_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.TextField(blank=True, null=True),
        ),
    ]
